Repository Xcov19/covidX, pull requests merged in 2020-09, with the labels that each got.

#27 Update main.yml
  .github/workflows/main.yml
Labels: bug, first-timers-only, good first issue, up-for-grabs

#26 Update gunicorn.conf.py
  gunicorn.conf.py
Labels: first-timers-only, good first issue, needs-review, up-for-grabs

#31 optional trailing slash for swagger yaml. added black psf. WORKSPACE …
  .pre-commit-config.yaml
  Readme.md
  WORKSPACE
  app.yaml
  covidX/urls.py
  requirements_dev.txt
Labels: enhancement, needs-review

#32 Update codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: bug, needs-review

#33 Feature/backend/config
  .gcloudignore
  .github/workflows/main.yml
  Readme.md
  app.yaml
  covidX/gae_settings.py
  covidX/settings.py
  requirements.txt
Labels: documentation, enhancement, needs-review, security fix

#35 updated to conform to appengine requirements
  app.yaml
  covidX/settings.py
  main.py
Labels: needs-review
