Repository Xcov19/covidX, pull requests merged in 2020-12, with the labels that each got.

#63 Feature/backend/auth0 drf
  .gitignore
  apps/apihealth/BUILD
  apps/apihealth/__init__.py
  apps/auth_zero/BUILD
  apps/auth_zero/__init__.py
  apps/auth_zero/admin.py
  apps/auth_zero/apps.py
  apps/auth_zero/auth0backend.py
  apps/auth_zero/migrations/0001_initial.py
  apps/auth_zero/migrations/0002_auto_20201207_1253.py
  apps/auth_zero/models.py
  apps/auth_zero/views.py
  apps/hrm/BUILD
  apps/hrm/__init__.py
  apps/hrm/migrations/0001_initial.py
  apps/hrm/migrations/__init__.py
  apps/workflow/migrations/__init__.py
  covidX/BUILD
  covidX/settings.py
  covidX/urls.py
Labels: bug, needs-review

#67 Update .env_sample file
  .env_sample
Labels: documentation

#66 MYC-88 #comment WIP refactor drf-jwt settings as per auth0backend.
  BUILD
  apps/auth_zero/BUILD
  apps/auth_zero/admin.py
  apps/auth_zero/apps.py
  apps/auth_zero/auth0backend.py
  apps/auth_zero/migrations/0003_auto_20201211_1219.py
  apps/auth_zero/models.py
  apps/auth_zero/templates/dashboard.html
  apps/auth_zero/urls.py
  apps/auth_zero/views.py
  covidX/BUILD
  covidX/settings.py
  covidX/urls.py
  requirements.txt
Labels: enhancement
