Repository Xcov19/covidX, pull requests merged in 2020-10, with the labels that each got.

#36 Dockerized bazel image.
  .gcloudignore
  .github/workflows/main.yml
  .gitignore
  BUILD
  Readme.md
  WORKSPACE
  covidX/BUILD
  covidX/settings.py
Labels: documentation, enhancement

#37 added missing cloud config file
  cloudbuild.yaml
Labels: enhancement

#39 verified with cloud local build
  cloudbuild.yaml
Labels: bug, enhancement

#41 remove version number
  cloudbuild.yaml
Labels: bug, enhancement

#45 Feature/backend/auth0 drf
  .deepsource.toml
  .github/workflows/main.yml
  .gitignore
  .idea
  BUILD
  Readme.md
  __init__.py
  apps/apihealth/BUILD
  apps/apihealth/serializer.py
  apps/apihealth/urls.py
  apps/apihealth/views.py
  apps/auth/migrations/__init__.py
  apps/auth/models.py
  apps/auth/static/app.css
  apps/auth/tests.py
  apps/auth/urls.py
  apps/auth_zero/BUILD
  apps/auth_zero/__init__.py
  apps/auth_zero/apps.py
  apps/auth_zero/auth0backend.py
  apps/auth_zero/migrations/__init__.py
  apps/auth_zero/templates/dashboard.html
  apps/auth_zero/templates/index.html
  apps/auth_zero/templates/layout.html
  apps/auth_zero/urls.py
  apps/auth_zero/views.py
  apps/hrm/models.py
  cloudbuild.yaml
  cloudbuild_test.yaml
  common/BUILD
  common/utils.py
  covidX/BUILD
  covidX/schema.py
  covidX/settings.py
  covidX/urls.py
  covidX/utils.py
  requirements.txt
  requirements_dev.txt
  secrets.sh
  secrets_test.sh
Labels: enhancement, needs-review

#46 remove unwanted garbage
  .idea
Labels: bug

#44 Algolia Package installation
  cloudbuild.yaml
  cloudbuild_test.yaml
  covidX/settings.py
  requirements.txt
  secrets.sh
Labels: Hacktoberfest, Hacktoberfest-approved, good first issue, merge-later, needs-review
