Repository Xcov19/covidX, pull requests merged in 2020-11, with the labels that each got.

#54 Feature/cloudops/docker gitpod
  .gitpod.yml
  .run/Dockerfile.run.xml
  BUILD
  Dockerfile
  Readme.md
  WORKSPACE
  covidX/settings.py
  requirements.txt
Labels: dependencies, documentation, enhancement

#55 MYC-152 #close #comment updated readme with gitpod snapshot
  Readme.md
Labels: prebuilt-in-gitpod

#51 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#56 Added common issues section to Readme.md
  Readme.md
Labels: documentation, first-timers-only, good first issue

#58 updated common issues in readme
  .gitignore
  Readme.md
Labels: documentation
