Repository Xcov19/covidX, pull requests merged in 2021-05, with the labels that each got.

#83 make markdown linter happy
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: bug

#117 Update pyopenssl and cryptography
  requirements.txt
Labels: dependencies, good first issue, security fix

#121 fixes hashes; remove allow-unsafe
  requirements.txt
Labels: bug, dependencies, security fix

#119 Master
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: dependencies, documentation, needs-review

#82 Docs/update local run readme
  .env_sample
  .gitignore
  Readme.md
Labels: documentation
