Repository Xcov19/covidX, pull requests merged in 2021-01, with the labels that each got.

#71 requirements dev and requirements.txt is need to be installed separately
  requirements_dev.txt
Labels: dependencies, good first issue

#73 document django secret key in readme
  Readme.md
Labels: documentation

#74 Dockerized repo
  Dockerfile
  WORKSPACE
  apps/auth_zero/migrations/0001_initial.py
  apps/auth_zero/migrations/0002_auto_20201207_1253.py
  apps/auth_zero/migrations/0003_auto_20201211_1219.py
  apps/hrm/migrations/0001_initial.py
  apps/hrm/migrations/__init__.py
  docker-compose.yml
  pre-start.sh
  up-script.sh
Labels: dependencies, enhancement, needs-review

#75 uses self certification on server
  up-script.sh
Labels: enhancement

#76 Present run
  .gcloudignore
  BUILD
  Dockerfile
  app.yaml
  cloudbuild.yaml
  covidX/BUILD
  covidX/settings/BUILD
  covidX/settings/base.py
  covidX/settings/dev.py
  covidX/wsgi.py
  docker-compose.yml
  manage.py
  pre-start.sh
  requirements.txt
  requirements_dev.txt
  secrets.sh
  up-script.sh
Labels: dependencies, enhancement
